import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { GlobalState } from '../../types';

const initialState: GlobalState = {
   darkMode: true,
   invoiceModal: false,
};

export const globalSlice = createSlice({
   name: 'global',
   initialState,
   // The `reducers` field lets us define reducers and generate associated actions
   reducers: {
      toggleTheme: (state) => {
         state.darkMode = !state.darkMode;
      },
      toggleInvoiceModal: (state) => {
         state.invoiceModal = !state.invoiceModal;
      },
   },
   // The `extraReducers` field lets the slice handle actions defined elsewhere,
   // including actions generated by createAsyncThunk or in other slices.
});

export const { toggleTheme, toggleInvoiceModal } = globalSlice.actions;

export default globalSlice.reducer;
