import { createSlice } from '@reduxjs/toolkit';
import { InvoiceState } from '../../types';
import data from '../../data/index.json';

const initialState: InvoiceState = {
   data: [...data.invoices],
   filtered_data: [...data.invoices],
};

export const invoiceSlice = createSlice({
   name: 'invoices',
   initialState,
   // The `reducers` field lets us define reducers and generate associated actions
   reducers: {
      filterInvoices: (state, action) => {},
   },
   // The `extraReducers` field lets the slice handle actions defined elsewhere,
   // including actions generated by createAsyncThunk or in other slices.
});

export const { filterInvoices } = invoiceSlice.actions;

export default invoiceSlice.reducer;
